export const CatalogActionType = {
    CREATE_NEW_ARTICLE:'[CATALOG] CREATE_NEW_ARTICLE',
    REMOVE_ARTICLE:'[CATALOG] REMOVE_ARTICLE:',
    UPDATE_ARTICLE:'[CATALOG] UPDATE_ARTICLE',
    ADD_COMMENT:'[CATALOG] ADD_COMMENT'
} as const