export const CatalogActionType = {
    LOAD_ARTICLES_START: '[CATALOG] LOAD_ARTICLES_START',
    LOAD_ARTICLES_SUCCESS: '[CATALOG] LOAD_ARTICLE_SUCCESS',
    LOAD_ARTICLES_FAILED: '[CATALOG] LOAD_ARTICLE_FAILED',

    LOAD_ITEM_BY_ID_START: '[CATALOG] LOAD_ITEM_BY_ID_START',
    LOAD_ITEM_BY_ID_SUCCESS: '[CATALOG] LOAD_ITEM_BY_ID_SUCCESS',
    LOAD_ITEM_BY_ID_FAILED: '[CATALOG] LOAD_ITEM_BY_ID_FAILED',

    CREATE_NEW_ARTICLE_START: '[CATALOG] CREATE_NEW_ARTICLE_START',
    CREATE_NEW_ARTICLE_SUCCESS: '[CATALOG] CREATE_NEW_ARTICLE_SUCCESS',
    CREATE_NEW_ARTICLE_FAILED: '[CATALOG] CREATE_NEW_ARTICLE_FAILED',

    REMOVE_ARTICLE_START: '[CATALOG] REMOVE_ARTICLE_START:',
    REMOVE_ARTICLE_SUCCESS: '[CATALOG] REMOVE_ARTICLE_SUCCESS:',
    REMOVE_ARTICLE_FAILED: '[CATALOG] REMOVE_ARTICLE_FAILED:',

    UPDATE_ARTICLE_START: '[CATALOG] UPDATE_ARTICLE_START',
    UPDATE_ARTICLE_SUCCESS: '[CATALOG] UPDATE_ARTICLE_SUCCESS',
    UPDATE_ARTICLE_FAILED: '[CATALOG] UPDATE_ARTICLE_FAILED',

    ADD_COMMENT_START: '[CATALOG] ADD_COMMENT_START',
    ADD_COMMENT_SUCCESS: '[CATALOG] ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILED: '[CATALOG] ADD_COMMENT_FAILED',

    ADD_CATEGORY_FILTER_VALUE: '[CATALOG] ADD_CATEGORY_FILTER_VALUE',
    ADD_SEARCH_STRING_FILTER_VALUE: '[CATALOG] ADD_SEARCH_STRING_FILTER_VALUE',
    ADD_PRICE_FILTER_VALUE: '[CATALOG] ADD_PRICE_FILTER_VALUE',
    CHANGE_CURRENT_PAGE:'[CATALOG] CHANGE_CURRENT_PAGE'
} as const