export const CatalogActionType = {
    LOAD_ARTICLE: '[CATALOG] LOAD_ARTICLE',
    LOAD_ARTICLE_SUCCESS: '[CATALOG] LOAD_ARTICLE_SUCCESS',
    LOAD_ARTICLE_FAILED: '[CATALOG] LOAD_ARTICLE_FAILED',
    CREATE_NEW_ARTICLE: '[CATALOG] CREATE_NEW_ARTICLE',
    CREATE_NEW_ARTICLE_SUCCESS: '[CATALOG] CREATE_NEW_ARTICLE_SUCCESS',
    CREATE_NEW_ARTICLE_FAILED: '[CATALOG] CREATE_NEW_ARTICLE_FAILED',
    REMOVE_ARTICLE: '[CATALOG] REMOVE_ARTICLE:',
    REMOVE_ARTICLE_SUCCESS: '[CATALOG] REMOVE_ARTICLE_SUCCESS:',
    REMOVE_ARTICLE_FAILED: '[CATALOG] REMOVE_ARTICLE_FAILED:',
    UPDATE_ARTICLE: '[CATALOG] UPDATE_ARTICLE',
    UPDATE_ARTICLE_SUCCESS: '[CATALOG] UPDATE_ARTICLE_SUCCESS',
    UPDATE_ARTICLE_FAILED: '[CATALOG] UPDATE_ARTICLE_FAILED',
    ADD_COMMENT: '[CATALOG] ADD_COMMENT',
    ADD_COMMENT_SUCCESS: '[CATALOG] ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILED: '[CATALOG] ADD_COMMENT_FAILED'
} as const