export const FilterActionType = {
    SET_MIN_PRICE_VALUE:'[FILTER] SET_MIN_PRICE_VALUE',
    SET_MAX_PRICE_VALUE:'[FILTER] SET_MAX_PRICE_VALUE',
    CHANGE_PRODUCER:'[FILTER] CHANGE_PRODUCER',
    CHANGE_IN_MARKET_TOGGLE: '[FILTER] CHANGE_IN_MARKET_TOGGLE',
    SET_SEARCH_QUERY:'[FILTER] SET_SEARCH_QUERY'
} as const