export const AuthActionTypes = {
    START_LOGIN: '[AUTH] START_LOGIN',
    LOGIN_SUCCESS: '[AUTH] LOGIN_SUCCESS',
    LOGIN_FAILED: '[AUTH] LOGIN_FAILED',
    LOGOUT: '[AUTH] LOGOUT',
    START_REGISTRATION: '[AUTH] START_REGISTRATION',
    REGISTRATION_SUCCESS: '[AUTH] REGISTRATION_SUCCESS',
    REGISTRATION_FAILED: '[AUTH] REGISTRATION_FAILED',
} as const