export const AuthActionTypes = {
    START_LOGIN: '[LOGIN] START_LOGIN',
    LOGIN_SUCCESS: '[LOGIN] LOGIN_SUCCESS',
    LOGIN_FAILED: '[LOGIN] LOGIN_FAILED',
    START_LOGOUT: '[LOGIN] START_LOGOUT',
    LOGOUT_SUCCESS: '[LOGIN] LOGOUT_SUCCESS',
    LOGOUT_FAILED: '[LOGIN] LOGOUT_FAILED',
} as const