export const AuthActionTypes = {
    LOGIN_START: '[AUTH] LOGIN_START',
    LOGIN_SUCCESS: '[AUTH] LOGIN_SUCCESS',
    LOGIN_FAILED: '[AUTH] LOGIN_FAILED',

    LOGOUT: '[AUTH] LOGOUT',

    REGISTRATION_START: '[AUTH] REGISTRATION_START',
    REGISTRATION_SUCCESS: '[AUTH] REGISTRATION_SUCCESS',
    REGISTRATION_FAILED: '[AUTH] REGISTRATION_FAILED',
} as const