export const CategoryActionsType = {
    CREATE_NEW_CATEGORY: '[CATEGORY] CREATE_NEW_CATEGORY',
    REMOVE_CATEGORY: '[CATEGORY] REMOVE_CATEGORY',
    UPDATE_CATEGORY: '[CATEGORY] UPDATE_CATEGORY',
} as const