export const CategoryActionsType = {
    START_NEW_CATEGORY_CREATION: '[CATEGORY] START_NEW_CATEGORY_CREATION',
    CREATE_NEW_CATEGORY_SUCCESS: '[CATEGORY] CREATE_NEW_CATEGORY_SUCCESS',
    CREATE_NEW_CATEGORY_FAILED: '[CATEGORY] CREATE_NEW_CATEGORY_FAILED',

    START_REMOVING_CATEGORY: '[CATEGORY] START_REMOVING_CATEGORY',
    REMOVE_CATEGORY_SUCCESS: '[CATEGORY] REMOVE_CATEGORY_SUCCESS',
    REMOVE_CATEGORY_FAILED: '[CATEGORY] REMOVE_CATEGORY_FAILED',

    START_FETCHING_CATEGORIES: '[CATEGORY] START_FETCHING_CATEGORIES',
    SET_CATEGORIES_SUCCESS: '[CATEGORY] SET_CATEGORIES_SUCCESS',
    SET_CATEGORIES_FAILED: '[CATEGORY] SET_CATEGORIES_FAILED',
} as const